spring.application.name=MA_OJT_Gradle

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/ma_ojt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway (Tắt tạm thời nếu chưa có file migration script)
spring.flyway.enabled=false
